export const CLIENT_LIST_MY_REQUEST = 'CLIENT_LIST_MY_REQUEST'
export const CLIENT_LIST_MY_SUCCESS = 'CLIENT_LIST_MY_SUCCESS'
export const CLIENT_LIST_MY_FAIL = 'CLIENT_LIST_MY_FAIL'
export const CLIENT_LIST_MY_RESET = 'CLIENT_LIST_MY_RESET'

export const CLIENT_LIST_ONE_REQUEST = 'CLIENT_LIST_ONE_REQUEST'
export const CLIENT_LIST_ONE_SUCCESS = 'CLIENT_LIST_ONE_SUCCESS'
export const CLIENT_LIST_ONE_FAIL = 'CLIENT_LIST_ONE_FAIL'
export const CLIENT_LIST_ONE_RESET = 'CLIENT_LIST_ONE_RESET'

export const CLIENT_DELETE_REQUEST = 'CLIENT_DELETE_REQUEST'
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS'
export const CLIENT_DELETE_FAIL = 'CLIENT_DELETE_FAIL'

export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST'
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS'
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL'
export const CLIENT_CREATE_RESET = 'CLIENT_CREATE_RESET'